[package]
name = "gui-kvstore"
authors = ["guinetik <guinetik@gmail.com>"]
version = "0.1.13"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"