[package]
name = "gui-kvstore"
authors = ["guinetik <guinetik@gmail.com>"]
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
rust-crypto = "^0.2"
rand = "0.3.0"
tabled = "0.7.0"